# The MIT License
# 
# Copyright (c) 2008 William T. Katz
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to 
# deal in the Software without restriction, including without limitation 
# the rights to use, copy, modify, merge, publish, distribute, sublicense, 
# and/or sell copies of the Software, and to permit persons to whom the 
# Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
# DEALINGS IN THE SOFTWARE.

"""A simple RESTful blog/homepage app for Google App Engine

This simple homepage application tries to follow the ideas put forth in the
book 'RESTful Web Services' by Leonard Richardson & Sam Ruby.  It follows a
Resource-Oriented Architecture where each URL specifies a resource that
accepts HTTP verbs.

Rather than create new URLs to handle web-based form submission of resources,
this app embeds form submissions through javascript.  The ability to send
HTTP verbs POST, PUT, and DELETE is delivered through javascript within the
GET responses.  In other words, a rich client gets transmitted with each GET.

This app's API should be reasonably clean and easily targeted by other 
clients, like a Flex app or a desktop program.
"""
__author__ = 'William T. Katz'

import datetime
import string
import re
import os
import cgi
import urllib
import urlparse

import logging

from google.appengine.ext import webapp
from google.appengine.api import users
from google.appengine.ext import db
from google.appengine.ext.webapp import template
from google.appengine.api import mail
from google.appengine.api import urlfetch

from handlers import restful
from utils import authorized
from utils import sanitizer
import models
import view
import config

import legacy_aliases   # This can be either manually created or 
                        # autogenerated using the drupal_uploader utility

# Functions to generate permalinks depending on type of article
permalink_funcs = {
    'article': lambda title,date: get_friendly_url(title),
    'blog entry': lambda title,date: str(date.year) + "/" + \
                        str(date.month) + "/" + get_friendly_url(title)
}

# We allow a mapping from some old url pattern to the current query 
#  using a regex's matched string.
def legacy_id_mapping(path, legacy_program):
    if legacy_program:
        if legacy_program == 'Drupal':
            url_match = re.match('node/(\d+)/?$', path)
            if url_match:
                return db.Query(models.blog.Article). \
                    filter('legacy_id =', url_match.group(1)). \
                    get()
        elif legacy_program == 'Serendipity':
            url_match = re.match('archives/(\d+)-.*\.html$', path)
            if url_match:
                return db.Query(models.blog.Article). \
                    filter('legacy_id =', url_match.group(1)).get()
    return None

# Module methods to handle incoming data
def get_datetime(time_string = None):
    if time_string:
        return datetime.datetime.strptime(time_string, '%Y-%m-%d %H:%M:%S')
    return datetime.datetime.now()

def get_format(format_string):
    if not format_string or format_string not in ['html', 'textile']:
        format_string = 'html'
    return format_string

def process_tag(tag_name, tags):
    # Check tag_name against all 'name' values in tags and coerce
    tag_name = tag_name.strip()
    lowercase_name = tag_name.lower()
    for tag in tags:
        if lowercase_name == tag['name'].lower():
            return tag['name']
    return tag_name

def get_tags(tags_string):
    logging.debug("get_tags: tag_string = %s", tags_string)
    if tags_string:
        from models.blog import Tag
        tags = Tag.list()
        logging.debug("  tags = %s", tags)
        return [process_tag(s, tags) 
                for s in tags_string.split(",") if s != '']
    return None
    
def get_friendly_url(title):
    return re.sub('-+', '-', 
                  re.sub('[^\w-]', '', 
                         re.sub('\s+', '-', title.strip())))

def get_html(body, markup_type):
    if markup_type == 'textile':
        from external.libs import textile
        return textile.textile(body)
    return body

def get_captcha(key):
    return ("%X" % abs(hash(str(key) + config.BLOG['title'])))[:6]

def get_sanitizer_func(handler, **kwargs):
    match_obj = re.match(r'.*;\s*charset=(?P<charset>[\w-]+)',  
                         handler.request.headers['CONTENT_TYPE'])
    kwlist = {}
    kwlist.update(kwargs)
    if match_obj:
        kwlist.update({ 'encoding': match_obj.group('charset').lower() })
    logging.debug("Content-type: %s", handler.request.headers['CONTENT_TYPE'])
    logging.debug("In sanitizer: %s", kwlist)
    return lambda html : sanitizer.sanitize_html(html, **kwlist)

def do_sitemap_ping():
    form_fields = { "sitemap": "%s/sitemap.xml" % (config.BLOG['root_url'],) }
    urlfetch.fetch(url="http://www.google.com/webmasters/tools/ping",
                   payload=urllib.urlencode(form_fields),
                   method=urlfetch.GET)

def process_embedded_code(article):
    # TODO -- Check for embedded code, escape opening triangular brackets
    # within code, and set article embedded_code strings so we can
    # use proper javascript.
    from utils import codehighlighter
    article.html, languages = codehighlighter.process_html(article.html)
    article.embedded_code = languages

def process_article_edit(handler, permalink):
    # For http PUT, the parameters are passed in URIencoded string in body
    body = handler.request.body
    params = cgi.parse_qs(body)
    for key,value in params.iteritems():
        params[key] = value[0]
    property_hash = restful.get_sent_properties(params.get,
        ['title',
         ('body', get_sanitizer_func(handler, trusted_source=True)),
         ('format', get_format),
         ('updated', get_datetime),
         ('tags', get_tags),
         ('html', get_html, 'body', 'format')])

    if property_hash:
        article = models.blog.Article.get_by_key_name('/' + permalink)
        if article.author.user != users.get_current_user():
            if not authorized.has_role(handler, "admin"): return
        before_tags = set(article.tags)
        for key,value in property_hash.iteritems():
            setattr(article, key, value)
        after_tags = set(article.tags)
        for removed_tag in before_tags - after_tags:
            models.blog.Tag.get_or_insert(removed_tag).counter.decrement()
        for added_tag in after_tags - before_tags:
            models.blog.Tag.get_or_insert(added_tag).counter.increment()
        process_embedded_code(article)
        article.put()
        restful.send_successful_response(handler, '/' + article.permalink)
        view.invalidate_cache()
    else:
        handler.error(400)

def process_article_submission(handler, article_type):
    property_hash = restful.get_sent_properties(handler.request.get, 
        ['title',
         ('body', get_sanitizer_func(handler, trusted_source=True)),
         'legacy_id',
         ('format', get_format),
         ('published', get_datetime),
         ('updated', get_datetime),
         ('tags', get_tags),
         ('html', get_html, 'body', 'format'),
         ('permalink', permalink_funcs[article_type], 'title', 'published')])

    if property_hash:
        author_user = users.get_current_user()
        author_name, author_nick = config.BLOG['authors'][author_user.email()]
        author = models.blog.Author.get_or_insert(
            author_nick, user=author_user, name=author_name)
        author.article_count += 1
        property_hash['author'] = author
        property_hash['format'] = 'html'   # For now, convert all to HTML
        property_hash['article_type'] = article_type
        article = models.blog.Article(**property_hash)
        article.set_associated_data(
            {'relevant_links': handler.request.get('relevant_links'),
             'amazon_items': handler.request.get('amazon_items')})
        process_embedded_code(article)
        db.put([article, author])
        # Ensure there is a year entity for this entry's year
        models.blog.Year.get_or_insert('Y%d' % (article.published.year,))
        # Update tags
        for key in article.tags:
            models.blog.Tag.get_or_insert(key).counter.increment()
        do_sitemap_ping()
        restful.send_successful_response(handler, '/' + article.permalink)
        view.invalidate_cache()
    else:
        handler.error(400)

def add_comment_tx(article_key, parent, property_hash, key_name):
    article = models.blog.Article.get(article_key)
    article.num_comments += 1
    comment = models.blog.Comment(parent=parent, key_name=key_name,
                                  **property_hash)
    comment.comment_id = article.next_comment_id
    article.next_comment_id += 1
    db.put([article, comment])
    return comment

def process_comment_submission(handler, article):
    sanitize_comment = get_sanitizer_func(handler,
                                          allow_attributes=['href', 'src'],
                                          blacklist_tags=['img'])
    property_hash = restful.get_sent_properties(handler.request.get, 
        ['name',
         'email',
         'homepage',
         'title',
         ('body', sanitize_comment),
         'key',
         'thread',    # If it's given, use it.  Else generate it.
         'captcha',
         ('published', get_datetime)])

    # If we aren't administrator, abort if bad captcha
    if not users.is_current_user_admin():
        if property_hash.get('captcha', None) != get_captcha(article.key()):
            logging.info("Received captcha (%s) != %s", 
                          property_hash.get('captcha', None),
                          get_captcha(article.key()))
            handler.error(401)      # Unauthorized
            return
        if 'thread' in property_hash:
            handler.error(403)
            return
        if not article.are_comments_allowed():
            handler.error(403)
            return
    if 'key' not in property_hash and 'thread' not in property_hash:
        handler.error(400)
        return

    # Find the parent comment
    key_name = None
    parent = article.key()
    if 'thread' in property_hash:
        comment_list = property_hash['thread'].split(',')
        key_name = '_' + comment_list[-1]
        if len(comment_list) > 1:
            thread_keys = sum([('Comment', '_'+x) for x in comment_list[:-1]], ())
            parent = db.Key.from_path(parent=parent, *thread_keys)
        del property_hash['thread']
    else:
        matchobj = re.match(r'[^#]+#comment-(?P<id>\d+)', 
                            property_hash['key'])
        if matchobj:
            logging.debug("Comment has parent: %s", matchobj.group('id'))
            comment_id = matchobj.group('id')
            parent = models.blog.Comment.all().ancestor(article).\
                filter('comment_id =', int(comment_id)).get()
        else:
            logging.debug("Comment is off main article")
        del property_hash['key']
    try:
        comment = db.run_in_transaction(add_comment_tx, article.key(),
                                        parent, property_hash, key_name)
    except:
        logging.info("Bad comment: %s", property_hash)
        handler.error(400)
        raise
        return
        
    # Notify the author of a new comment
    if config.BLOG['send_comment_notification']:
        author_email = article.author.user.email()
        recipient = (config.BLOG['authors'][author_email][0],
                     author_email)
        body = ("A new comment has just been posted on %s/%s by %s."
                % (config.BLOG['root_url'], article.permalink, comment.name))
        mail.send_mail(sender=config.BLOG['email'],
                       to="%s <%s>" % recipient,
                       subject="New comment by %s" % (comment.name,),
                       body=body)

    # Render just this comment and send it to client
    view_path = view.find_file(view.templates, "bloog/blog/comment.html")
    response = template.render(
        os.path.join("views", view_path),
        { 'comment': comment, "use_gravatars": config.BLOG["use_gravatars"] },
        debug=config.DEBUG)
    handler.response.out.write(response)
    view.invalidate_cache()

def render_article(handler, article):
    if article:
        # Check if client is requesting javascript and
        # return json if javascript is #1 in Accept header.
        try:
            accept_list = handler.request.headers['Accept']
        except KeyError:
            logging.error("Had no accept header: %s", handler.request.headers)
            accept_list = None
        if accept_list and accept_list.split(',')[0] == 'application/json':
            handler.response.headers['Content-Type'] = 'application/json'
            handler.response.out.write(article.to_json())
        else:
            # Generate two parts of a captcha that will use
            # display:none in between.  This step in the anti-spam
            # war race due to the following article:
            # http://techblog.tilllate.com/2008/07/20/ten-methods-to-obfuscate-e-mail-addresses-compared/
            captcha = get_captcha(article.key())
            current_user = users.get_current_user()
            show_edit_controls = (article.author.user == current_user)
            show_edit_controls |= users.is_current_user_admin()
            page = view.ViewPage()
            page.render(handler, { "is_big": article.is_big(),
                                   "allow_comments": article.are_comments_allowed(),
                                   "article": article,
                                   "show_edit_controls": show_edit_controls,
                                   "captcha1": captcha[:3],
                                   "captcha2": captcha[3:6],
                                   "use_gravatars": config.BLOG['use_gravatars'],
            })
    else:
        # This didn't fall into any of our pages or aliases.
        # Page not found.
        handler.error(404)
        view.ViewPage(cache_time=36000). \
             render(handler, {'module_name': 'blog', 
                              'handler_name': 'notfound'})

class NotFoundHandler(webapp.RequestHandler):
    def get(self):
        self.error(404)
        view.ViewPage(cache_time=36000).render(self)

class UnauthorizedHandler(webapp.RequestHandler):
    def get(self):
        self.error(403)
        view.ViewPage(cache_time=36000).render(self)

class RootHandler(restful.Controller):
    def get(self):
        logging.debug("RootHandler#get")
        page = view.ViewPage()
        page.render_query(
            self, 'articles', 
            db.Query(models.blog.Article). \
               filter('article_type =', 'blog entry').order('-published'))

    @authorized.role("author")
    def post(self):
        logging.debug("RootHandler#post")
        process_article_submission(handler=self, article_type='article')

class ArticlesHandler(restful.Controller):
    def get(self):
        logging.debug("ArticlesHandler#get")
        page = view.ViewPage()
        page.render_query(
            self, 'articles',
            db.Query(models.blog.Article). \
               filter('article_type =', 'article').order('title'),
            num_limit=20)

# Articles are off root url
# TODO -- Make it DRY by combining Article/MonthHandler
class ArticleHandler(restful.Controller):
    def get(self, path):
        logging.debug("ArticleHandler#get on path (%s)", path)
        # Handle precomputed legacy aliases
        # TODO: Use hash for case-insensitive lookup
        for alias in legacy_aliases.redirects:
            if path.lower() == alias.lower():
                self.redirect(legacy_aliases.redirects[alias])
                return

        # Check undated pages
        article = models.blog.Article.get_by_key_name('/' + path)
        if not article:
            # This lets you map arbitrary URL patterns like /node/3
            #  to article properties, e.g. 3 -> legacy_id property
            article = legacy_id_mapping(path,
                                        config.BLOG["legacy_blog_software"])
            if article and config.BLOG["legacy_entry_redirect"]:
                self.redirect('/' + article.permalink)
                return
        render_article(self, article)

    @restful.methods_via_query_allowed    
    def post(self, path):
        article = models.blog.Article.get_by_key_name('/'+path)
        process_comment_submission(self, article)

    @authorized.role("author")
    def put(self, path):
        logging.debug("ArticleHandler#put")
        process_article_edit(self, permalink = path)

    @authorized.role("author")
    def delete(self, path):
        """
        By using DELETE on /Article, /Comment, /Tag, you can delete the first 
         entity of the desired kind.
        This is useful for writing utilities like clear_datastore.py.  
        """
        # TODO: Add DELETE for articles off root like blog entry DELETE.
        model_class = path.lower()
        logging.debug("ArticleHandler#delete on %s", path)

        def delete_entity(query):
            target = query.get()
            if target:
                if hasattr(target, 'title'):
                    title = target.title
                elif hasattr(target, 'name'):
                    title = target.name
                else:
                    title = ''
                logging.debug('Deleting %s %s', model_class, title)
                target.delete()
                self.response.out.write('Deleted %s %s' % (model_class, title))
                view.invalidate_cache()
            else:
                self.response.set_status(204, 'No more %s entities' % (model_class,))
                
        if model_class == 'article':
            if not authorized.has_role(self, "admin"): return
            query = models.blog.Article.all()
            delete_entity(query)
        elif model_class == 'comment':
            if not authorized.has_role(self, "admin"): return
            query = models.blog.Comment.all()
            delete_entity(query)
        elif model_class == 'tag':
            if not authorized.has_role(self, "admin"): return
            query = models.blog.Tag.all()
            delete_entity(query)
        else:
            article = models.blog.Article.get_by_key_name('/'+path)
            if article.author.user != users.get_current_user():
                if not authorized.has_role(self, "admin"): return
            for key in article.tags:
                models.blog.Tag.get_or_insert(key).counter.decrement()
            article.delete()
            view.invalidate_cache()
            restful.send_successful_response(self, "/")

# Blog entries are dated articles
class BlogEntryHandler(restful.Controller):
    def get(self, year, month, perm_stem):
        logging.debug("BlogEntryHandler#get for year %s, "
                      "month %s, and perm_link %s", 
                      year, month, perm_stem)
        article = models.blog.Article.get_by_key_name('/%s/%s/%s' %
                                                      (year, month, perm_stem))
        render_article(self, article)

    @restful.methods_via_query_allowed    
    def post(self, year, month, perm_stem):
        logging.debug("Adding comment for blog entry %s", self.request.path)
        article = models.blog.Article.get_by_key_name('/%s/%s/%s' %
                                                      (year, month, perm_stem))
        if article:
            process_comment_submission(self, article)
        else:
            logging.debug("No article attached to submitted comment")
            self.error(400)

    @authorized.role("author")
    def put(self, year, month, perm_stem):
        permalink = '%s/%s/%s' % (year, month, perm_stem)
        logging.debug("BlogEntryHandler#put")
        process_article_edit(handler = self, permalink = permalink)

    @authorized.role("author")
    def delete(self, year, month, perm_stem):
        permalink = '/%s/%s/%s' % (year, month, perm_stem)
        logging.debug("Deleting blog entry %s", permalink)
        article = models.blog.Article.get_by_key_name(permalink)
        if article.author.user != users.get_current_user():
            if not authorized.has_role(self, "admin"): return
        for key in article.tags:
            models.blog.Tag.get_or_insert(key).counter.decrement()
        article.delete()
        view.invalidate_cache()
        restful.send_successful_response(self, "/")

class TagHandler(restful.Controller):
    def get(self, encoded_tag):
        tag =  re.sub('(%25|%)(\d\d)', 
                      lambda cmatch: chr(string.atoi(cmatch.group(2), 16)),                 
                      encoded_tag)   # No urllib.unquote in AppEngine?
        page = view.ViewPage()
        page.render_query(
            self, 'articles', 
            db.Query(models.blog.Article).filter('tags =',        
                                                 tag).order('-published'), 
                                                {'tag': tag})

class SearchHandler(restful.Controller):
    def get(self):
        page = view.ViewPage()
        if not config.BLOG['use_google_cse']:
            from google.appengine.api import datastore_errors
            search_term = self.request.get("s")
            query_string = 's=' + urllib.quote_plus(search_term) + '&'
            try:
                page.render_query(
                    self, 'articles', 
                    models.blog.Article.all().search(search_term). \
                        order('-published'), 
                    {'search_term': search_term, 'query_string': query_string})
            except datastore_errors.NeedIndexError:
                page.render(self, {'search_term': search_term,
                                   'search_error_message': """
                                   Sorry, full-text searches are currently limited
                                   to single words until a later AppEngine update.
                                   """})
        else:
            page.render(self)


class YearHandler(restful.Controller):
    def get(self, year):
        logging.debug("YearHandler#get for year %s", year)
        start_date = datetime.datetime(string.atoi(year), 1, 1)
        end_date = datetime.datetime(string.atoi(year), 12, 31, 23, 59, 59)
        page = view.ViewPage()
        page.render_query(
            self, 'articles', 
            db.Query(models.blog.Article).order('-published'). \
               filter('published >=', start_date). \
               filter('published <=', end_date), 
            {'title': 'Articles for ' + year, 'year': year})

class MonthHandler(restful.Controller):
    def get(self, year, month):
        logging.debug("MonthHandler#get for year %s, month %s", year, month)
        start_date = datetime.datetime(string.atoi(year), 
                                       string.atoi(month), 1)
        end_date = datetime.datetime(string.atoi(year), 
                                     string.atoi(month), 31, 23, 59, 59)
        page = view.ViewPage()
        page.render_query(
            self, 'articles', 
            db.Query(models.blog.Article).order('-published'). \
               filter('published >=', start_date). \
               filter('published <=', end_date), 
            {'title': 'Articles for ' + month + '/' + year, 
             'year': year, 'month': month})

    @authorized.role("author")
    def post(self, year, month):
        """ Add a blog entry. Since we are POSTing, the server handles 
            creation of the permalink url. """
        logging.debug("MonthHandler#post on date %s, %s", year, month)
        process_article_submission(handler=self, article_type='blog entry')
        
class AtomHandler(webapp.RequestHandler):
    def get(self):
        logging.debug("Sending Atom feed")
        articles = db.Query(models.blog.Article). \
                      filter('article_type =', 'blog entry'). \
                      order('-published').fetch(limit=10)
        updated = ''
        if articles:
            updated = articles[0].rfc3339_updated()
        
        self.response.headers['Content-Type'] = 'application/atom+xml'
        page = view.ViewPage()
        page.render(self, {"blog_updated_timestamp": updated, 
                           "articles": articles, "ext": "xml"})

class SitemapHandler(webapp.RequestHandler):
    def get(self):
        logging.debug("Sending Sitemap")
        articles = db.Query(models.blog.Article).order('-published').fetch(1000)
        if articles:
          self.response.headers['Content-Type'] = 'text/xml'
          page = view.ViewPage()
          page.render(self, {
              "articles": articles,
              "ext": "xml",
              "root_url": config.BLOG['root_url']
          })

class CseHandler(webapp.RequestHandler):
    """Handler for custom search engine definition file."""
    def get(self):
        self.response.headers['Content-Type'] = 'text/xml'
        page = view.ViewPage()
        page.render(self, {
            "ext": "xml",
            "blog_base": urlparse.urlparse(config.BLOG['root_url']).netloc,
        })

class AuthorHandler(webapp.RequestHandler):
    """Handler for author pages."""
    def get(self, author_nick):
        author = models.blog.Author.get_by_key_name(author_nick)
        if not author:
            self.error(404)
            view.ViewPage(cache_time=36000). \
                 render(self, {'module_name': 'blog', 
                               'handler_name': 'notfound'})
        page = view.ViewPage()
        page.render_query(
            self, 'articles',
            db.Query(models.blog.Article).filter('author =',        
                                                 author).order('-published'), 
                                                {'author': author})
